### ISSUE TITLE
illegal activity

### ISSUE THREAD

**Issue by mr-foobarian** [M22404/daily-amogus#1]
Stop this at once.

**Comment by hemisemidemipresent** [comment]
why are u grass

**Comment by hemisemidemipresent** [comment]
when ur pfp is grass to compensate for the lack of grass you seem to touch, or you have a certain attraction towards grass

**Comment by foo-cs** [comment]
lack of a better image in my gallery and i can't currently be bothered to get a better pfp suitable for github

**Comment by hemisemidemipresent** [comment]
ur pfp has been resolved
